### ISSUE TITLE
A few execution issues

### ISSUE THREAD

**Issue by natalysheinin** [igniteflow/violent-python#1]
Hey, noticed a few issues with your code, I used it and then modified a bit to make a bit more sense.

1) Your program prints the last string in the dictionary.txt and never actually saves the correct password. This is because your password variable and result variable are the same:

`password = None
    result = None
    zip_file = zipfile.ZipFile(zipfilename)
    with open(dictionary, 'r') as f:
        for line in f.readlines():
            password = line.strip('\n')
            try:
                zip_file.extractall(pwd=password)
                result = 'Password found: %s' % password`

2) You need to print something else as result if the dictionary.txt is insufficient and unable to find the correct password.
So at the end of the execution of the loop, I added:
`if not result:
        result = 'Unable to crack '
    print result
`
3) I haven't implemented this yet - but you need to add a stopping mechanism to the loop in the case that the password is found, there is no point to continue execution- its a waste of running time & memory.

**Comment by DemersM** [comment]
+1

**Comment by prdcsm** [comment]
I think there is no need to add the working password to any variable, just print it out if extraction is successful. Also, breaking the loop there prevents the script from running all the way to the end of the wordlist. Works for me:)

```
zip_file.extractall(pwd=password)
            print("match found: " + password)
            break
```
